baseURL: https://brule.info/
languageCode: fr
title: Antoine Brûlé
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
    disableXML: true
    minifyOutput: true

defaultContentLanguage: fr
languages:
    #en:
    #    languageName: English
    #    weight: 2
    #    profileMode:
    #        enabled: true
    #        title: Antoine Brûlé
    #        buttons:
    #            - name: CV
    #              url: cv
    #            - name: Projects
    #              url: projects
    #    menu:
    #        main:
    #            - identifier: cv
    #              name: CV
    #              url: /cv
    #              weight: 10
    #            - identifier: projects
    #              name: Projects
    #              url: /projects
    #              weight: 20
    #    description: "Antoine Brûlé's personal website"

    fr:
        languageName: Français
        weight: 1
        profileMode:
            enabled: true
            title: Antoine Brûlé
            buttons:
                - name: CV
                  url: cv
                - name: Projets
                  url: projects
        menu:
            main:
                - identifier: cv
                  name: CV
                  url: /cv
                  weight: 10
                - identifier: projects
                  name: Projets
                  url: /projects
                  weight: 20
        description: "Site personnel d'Antoine Brûlé"

params:
    env: production
    title: Antoine Brûlé
    keywords: [Blog, Portfolio, CV]
    author: Antoine Brûlé
    DateFormat: "January 2, 2006"
    defaultTheme: light
    disableThemeToggle: true

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: false
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
